version: '3'
services:

  postgres:
    container_name: odoo-db
    image: "postgres:10.0"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    expose:
      - 5432
    ports:
      - 5433:5432

  odoo12:
    container_name: odoo12
    image: "idazco/odoo:12-latest"

#    build:
#      context: .
#      dockerfile: Dockerfile

    volumes:
      - ./run-demo.conf:/etc/odoo/odoo.conf:ro
    depends_on:
      - postgres
    links:
      - postgres:db
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=compose