version: '3'
services:

  postgres:
    container_name: odoo-db
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    expose:
      - 5432
    ports:
      - 5433:5432

  odoo10:
    container_name: odoo10
    image: "idazco/odoo:10-latest"

    volumes:
      - ./run-demo.conf:/etc/odoo/odoo.conf:ro
    depends_on:
      - postgres
    links:
      - postgres:db
    ports:
      - 8080:8080